from typing import Any

from _typeshed import Incomplete

from . import STATUS_ELEMENTS as STATUS_ELEMENTS
from .dclass import StatusElementNotification as StatusElementNotification
from .queue import NotificationQueue as NotificationQueue

NotificationType: Incomplete

def toast_stn(*args: Any, **kwargs: Any) -> None: ...
def balloons_stn(*args: Any, **kwargs: Any) -> None: ...
def snow_stn(*args: Any, **kwargs: Any) -> None: ...
def success_stn(*args: Any, **kwargs: Any) -> None: ...
def info_stn(*args: Any, **kwargs: Any) -> None: ...
def error_stn(*args: Any, **kwargs: Any) -> None: ...
def warning_stn(*args: Any, **kwargs: Any) -> None: ...
def exception_stn(*args: Any, **kwargs: Any) -> None: ...
def notify(remove: bool = True, notification_type: NotificationType | None = None) -> None: ...
def create_notification(*args: Any, **kwargs: Any) -> StatusElementNotification: ...
def get_notifications(notification_type: NotificationType) -> NotificationQueue: ...
