from .notification_dataclass import StatusElementNotification as StatusElementNotification
from .notification_queue import NotificationPriorityQueue as NotificationPriorityQueue
from typing import Any, Callable, Literal

class RerunnableStatusElement:
    def __init__(self, base_widget: Callable[..., Any]) -> None: ...
    @property
    def session_state_key(self) -> str: ...
    @property
    def base_widget(self) -> Callable[..., Any]: ...
    @property
    def name(self) -> str: ...
    @property
    def notifications(self) -> NotificationPriorityQueue: ...
    def setup_queue(self) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> None: ...
    def create_notification(self, *args: Any, **kwargs: Any) -> StatusElementNotification: ...
    def notify(self, remove: bool = True, priority: int | None = None, priority_type: Literal['le', 'lt', 'ge', 'gt', 'eq'] = 'eq') -> None: ...
